### ISSUE TITLE
市区町村ハザードマップ

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/hachioji-hazardmap#3]
## 課題

ハザードマップの Web アプリとしてはすでに https://disaportal.gsi.go.jp/ があるが、あくまで汎用的なもののため市区町村固有の事情を反映できない。

八王子市では、

- 市で内浸水深のデータを取っていて、市のハザードマップに反映している
- 浸水継続時間等の情報は八王子市ではあまり意味がないため、あえてハザードマップに載せていない

といった事情がある。

## 提案

市区町村でカスタマイズできる Web ハザードマップテンプレート。
GitHub の Template Repository として Web ハザードマップのテンプレートを作って、これを使えば設定ファイルをちょっといじったり、簡単な CSV なんかを足したりするだけで、市区町村オリジナルのハザードマップを作れるようにする。

### 最低限やりたい

- [x] https://disaportal.gsi.go.jp/hazardmap/copyright/opendata.html を使って重ねるハザードマップの簡易版作成
- [x] GitHub Pages にデプロイ
- [x] 対象の市区町村や利用するレイヤを設定ファイルから変更できるようにする
- [x] CSV で独自の情報を追加できるようにする

### できればやりたい

- [ ] 八王子市の内浸水深データを WMTS で提供
- [ ] 設定ファイルから↑を追加できるようにする

**Comment by sankichi92** [comment]
test

**Comment by smellman** [comment]
> 八王子市の内浸水深データを WMTS で提供

WMTSにこだわらずにXYZタイルにすればLeafletなどで簡単に読めます。
QGIS 3.22ならプロセッシングツールボックス->ラスタツール->XYZタイルの生成でいけると思います。

**Comment by sankichi92** [comment]
ありがとうございます！
4日前は地理院タイルと同じようにサーバサイドから提供かなと思ってたんですが、ファイルを読むのが楽そうですね。
QGIS でのXYZタイル作成方法もありがとうございます。
まだ Shapefile から XYZ タイルに至るまでの道筋全体は見えていないですが、続きは https://github.com/sankichi92/hachioji-hazardmap/issues/6 でやっていこうと思います。
